nohup: ignoring input
WARNING: While bind mounting '/mnt/stomics/alignment/reads:/mnt/stomics/alignment/reads': destination is already in the mount point list
WARNING: While bind mounting '/mnt/stomics/alignment/reference:/mnt/stomics/alignment/reference': destination is already in the mount point list
Error code: SAW-A10166

EXITING because of FATAL ERROR: could not open genome file /mnt/stomics/alignment/reference/STAR_SJ100/genomeParameters.txt
SOLUTION: check that the path to genome files, specified in --genomeDir is correct and the files are present, and have user read permsissions

Apr 21 07:31:46 ...... FATAL ERROR, exiting

/opt/pipeline/merge/ST_BarcodeMap_v0.0.2 --in /mnt/stomics/alignment/output/00.mapping/tongue-5_read_1.barcodeReadsCount.txt --out /mnt/stomics/alignment/output/01.merge/tongue-5.barcodeReadsCount.txt --action 2 
spatialRNADrawMap, time used: 0 seconds
[W::hts_set_opt] Cannot change block size for this format
SAW-A20003 SAW-A20001 Failed to read bam header: /mnt/stomics/alignment/output/00.mapping/tongue-5_read_1.Aligned.sortedByCoord.out.bam
terminate called after throwing an instance of 'std::runtime_error'
  what():  SAW-A20001 Failed to read bam header: /mnt/stomics/alignment/output/00.mapping/tongue-5_read_1.Aligned.sortedByCoord.out.bam
/usr/local/bin/count: line 1: 195050 Aborted                 (core dumped) /opt/pipeline/count/Bam2Gem_v2.2.1 $*
2022-04-21 07:31:59.881477: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/python3.8/lib/python3.8/site-packages/cv2/../../lib64:/opt/binary:/.singularity.d/libs
2022-04-21 07:31:59.881526: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
/usr/local/python3.8/lib/python3.8/site-packages/geopandas/_compat.py:111: UserWarning: The Shapely GEOS version (3.8.0-CAPI-1.13.1 ) is incompatible with the GEOS version PyGEOS was compiled with (3.10.1-CAPI-1.16.0). Conversions between both will be slow.
  warnings.warn(
2022-04-21 07:32:02 Stereo INFO: read_gef begin ...
HDF5-DIAG: Error detected in HDF5 (1.12.1) thread 0:
  #000: H5F.c line 620 in H5Fopen(): unable to open file
    major: File accessibility
    minor: Unable to open file
  #001: H5VLcallback.c line 3501 in H5VL_file_open(): failed to iterate over available VOL connector plugins
    major: Virtual Object Layer
    minor: Iteration failed
  #002: H5PLpath.c line 578 in H5PL__path_table_iterate(): can't iterate over plugins in plugin path '(null)'
    major: Plugin for dynamically loaded library
    minor: Iteration failed
  #003: H5PLpath.c line 620 in H5PL__path_table_iterate_process_path(): can't open directory: /usr/local/hdf5/lib/plugin
    major: Plugin for dynamically loaded library
    minor: Can't open directory or file
  #004: H5VLcallback.c line 3351 in H5VL__file_open(): open failed
    major: Virtual Object Layer
    minor: Can't open object
  #005: H5VLnative_file.c line 97 in H5VL__native_file_open(): unable to open file
    major: File accessibility
    minor: Unable to open file
  #006: H5Fint.c line 1834 in H5F_open(): unable to open file: name = '/mnt/stomics/alignment/output/04.tissuecut/tongue-5.tissue.gef', tent_flags = 0
    major: File accessibility
    minor: Unable to open file
  #007: H5FD.c line 723 in H5FD_open(): open failed
    major: Virtual File Layer
    minor: Unable to initialize object
  #008: H5FDsec2.c line 352 in H5FD__sec2_open(): unable to open file: name = '/mnt/stomics/alignment/output/04.tissuecut/tongue-5.tissue.gef', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0
    major: File accessibility
    minor: Unable to open file
HDF5-DIAG: Error detected in HDF5 (1.12.1) thread 0:
  #000: H5L.c line 938 in H5Lexists(): invalid location identifier
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.12.1) thread 0:
  #000: H5D.c line 276 in H5Dopen2(): invalid location identifier
    major: Invalid arguments to routine
    minor: Inappropriate type
failed open dataset: /geneExp/bin200/expression
HDF5-DIAG: Error detected in HDF5 (1.12.1) thread 0:
  #000: H5D.c line 276 in H5Dopen2(): invalid location identifier
    major: Invalid arguments to routine
    minor: Inappropriate type
failed open dataset: /geneExp/bin200/gene
HDF5-DIAG: Error detected in HDF5 (1.12.1) thread 0:
  #000: H5A.c line 449 in H5Aopen(): invalid location identifier
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: H5VLint.c line 1749 in H5VL_vol_object(): invalid identifier type to function
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.12.1) thread 0:
  #000: H5A.c line 698 in H5Aread(): not an attribute
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.12.1) thread 0:
  #000: H5A.c line 1624 in H5Aclose(): not an attribute
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.12.1) thread 0:
  #000: H5A.c line 449 in H5Aopen(): invalid location identifier
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: H5VLint.c line 1749 in H5VL_vol_object(): invalid identifier type to function
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.12.1) thread 0:
  #000: H5A.c line 698 in H5Aread(): not an attribute
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.12.1) thread 0:
  #000: H5A.c line 449 in H5Aopen(): invalid location identifier
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: H5VLint.c line 1749 in H5VL_vol_object(): invalid identifier type to function
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.12.1) thread 0:
  #000: H5A.c line 698 in H5Aread(): not an attribute
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.12.1) thread 0:
  #000: H5A.c line 449 in H5Aopen(): invalid location identifier
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: H5VLint.c line 1749 in H5VL_vol_object(): invalid identifier type to function
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.12.1) thread 0:
  #000: H5A.c line 698 in H5Aread(): not an attribute
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.12.1) thread 0:
  #000: H5A.c line 449 in H5Aopen(): invalid location identifier
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: H5VLint.c line 1749 in H5VL_vol_object(): invalid identifier type to function
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.12.1) thread 0:
  #000: H5A.c line 698 in H5Aread(): not an attribute
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.12.1) thread 0:
  #000: H5A.c line 449 in H5Aopen(): invalid location identifier
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: H5VLint.c line 1749 in H5VL_vol_object(): invalid identifier type to function
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.12.1) thread 0:
  #000: H5A.c line 698 in H5Aread(): not an attribute
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.12.1) thread 0:
  #000: H5A.c line 449 in H5Aopen(): invalid location identifier
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: H5VLint.c line 1749 in H5VL_vol_object(): invalid identifier type to function
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.12.1) thread 0:
  #000: H5A.c line 698 in H5Aread(): not an attribute
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.12.1) thread 0:
  #000: H5A.c line 1624 in H5Aclose(): not an attribute
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.12.1) thread 0:
  #000: H5Dio.c line 168 in H5Dread(): dset_id is not a dataset ID
    major: Invalid arguments to routine
    minor: Inappropriate type
2022-04-21 07:32:02 Stereo INFO: the martrix has 0 cells, and 0 genes.
HDF5-DIAG: Error detected in HDF5 (1.12.1) thread 0:
  #000: H5Dio.c line 168 in H5Dread(): dset_id is not a dataset ID
    major: Invalid arguments to routine
    minor: Inappropriate type
Traceback (most recent call last):
  File "cell_cluster_pyc_20220329/spatial_cluster.py", line 85, in <module>
  File "cell_cluster_pyc_20220329/spatial_cluster.py", line 80, in main
  File "cell_cluster_pyc_20220329/spatial_cluster.py", line 32, in spatial_cluster
  File "/usr/local/python3.8/lib/python3.8/site-packages/stereopy-0.2.4-py3.8.egg/stereo/io/reader.py", line 469, in read_gef
    (zip(np.right_shift(uniq_cells, 32), np.bitwise_and(uniq_cells, 0xffff))))).astype('uint32')
TypeError: ufunc 'right_shift' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
HDF5-DIAG: Error detected in HDF5 (1.12.1) thread 0:
  #000: H5D.c line 320 in H5Dclose(): not a dataset ID
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.12.1) thread 0:
  #000: H5S.c line 491 in H5Sclose(): not a dataspace
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.12.1) thread 0:
  #000: H5D.c line 320 in H5Dclose(): not a dataset ID
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.12.1) thread 0:
  #000: H5S.c line 491 in H5Sclose(): not a dataspace
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.12.1) thread 0:
  #000: H5F.c line 707 in H5Fclose(): not a file ID
    major: Invalid arguments to routine
    minor: Inappropriate type
Traceback (most recent call last):
  File "./saturation/v2.2.1/ST_Saturation.py", line 196, in <module>
  File "./saturation/v2.2.1/ST_Saturation.py", line 48, in main
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/stomics/alignment/output/02.count/tongue-5.Aligned.sortedByCoord.out.merge.q10.dedup.target.bam.summary.stat'
SAW-A90004
